name: Perbarui MAC Portal Otomatis

on:
  schedule:
    # Menggunakan format cron untuk berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch: # Memungkinkan Anda menjalankan alur kerja ini secara manual

jobs:
  update-link:
    runs-on: ubuntu-latest

    steps:
    # 1. Panggil repositori Anda
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-state: '3.x'

    # 3. Instal library yang dibutuhkan
    - # 5. Commit dan Push perubahan kembali ke GitHub
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # UBAH DISINI: Suruh Git mendeteksi file playlist.m3u yang baru dibuat
        git add playlist.m3u
        git diff-index --quiet HEAD || git commit -m "Otomatis: Perbarui playlist.m3u setiap 6 jam"
        git pushit commit -m "Otomatis: Perbarui MAC portal setiap 6 jam"
        git push
