name: Refresh M3U Portal

on:
  schedule:
    # Berjalan otomatis setiap 6 jam sekali
    - cron: '0 */6 * * *'
  workflow_dispatch: # Memungkinkan tombol "Run workflow" manual

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Converter Script
      run: python updater.py

    - - name: Commit and Push if changes exist
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add *.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-refresh all M3U playlists" && git push)
